### ISSUE TITLE
Provide License Acquired Date

### ISSUE THREAD

**Issue by under3415** [microsoft/Microsoft-Store-Services#8]
Instructions for implementing trial version of the app refers devs to ExpirationDate field, but this field returns year 9999 for free apps and unlimited trials. Time limited trials are very limited in options  and very strict as they don't allow users to start the app at all. 

In order to implement more flexible trial version,  devs need the start date,  but devs cannot easily establish when the user acquired the app.  One can try to store something locally (unreliable, not multi device aware), or use a web service (expensive, complex, privacy issues). 

Best solution is for store to expose "license acquired date". 

This would free devs to have more flexible trial version solutions without adding cost or complexity.  For example, have a free app with a month honeymoon period after which some features are blocked or nagging to pay  starts. 

Can you please add this? 

This would fit well with "dev friendly store"  win11 announcement! 

https://docs.microsoft.com/en-us/windows/uwp/monetize/exclude-or-limit-features-in-a-trial-version-of-your-app#step-4-get-an-apps-trial-expiration-date

**Comment by CameronGoodwin** [comment]
Hi @under3415!
Yes, the LicenseToken and XStore License structures currently do not provide the AcquiredDate which would help enable this scenario more easily as you outlined.  I will pass that request over to the team that owns those structures.

In the meantime if this is important for upcoming plans you have, you could implement this flow as you outlined if your app connects through your own services.  The AcquiredDate is provided when you call the Collections Query endpoint for the product so that would tell you when that specific user downloaded / acquired the game.  But again, this wouldn't work for an offline app as the call to your custom service would not work to gate access and features.

**Comment by CameronGoodwin** [comment]
Another option is that again if your app has an online service that it relies on, you could check the license and if this is the first time you have seen this user (your own app's user tracking) you put a timestamp in your own DB to track when they first game to the game and allow them access for the honeymoon period.  Then after that they are required to have a valid license for the full access to the title.

**Comment by CameronGoodwin** [comment]
The addition of the AcquiredDate may not be accepted by the feature team because the licenses are based on a hierarchy in some cases.  Such that there may be multiple licenses to a device from different users.  The user who has the highest tier license takes precedence over the others.  

So if the device has a license for user A that is 2 months old vs user B that is 1 day old, I would presume that the older one would take priority unless they are different tiers.  So user B in the logic would look like they were older than a new user and possibly be blocked from access to the content.

**Comment by under3415** [comment]
Hi
Thanks for taking the time to reply.

I can put a timestamp in my own local database or a file, but if the user uninstalls the app that is lost and honeymoon starts again. Obviously building an online service would solve the issue, but that costs money and there are privacy, regulation, CX, and support issues, so that's not an option. I would be pretty  peeved off if some small app asked me to establish an online profile, when I really don't need anything online from them (it's not an online storage app).

I am not sure I understand your comments about difficulties related to multiple users. Why is this not an issue for the expiry date?

But if they cannot provide an acquired date, they could return something more useful in expiry date instead. For example, when there is no trial expiry date, instead of 9999-01-01 they could return acquired date plus a 1,000 years. Devs could then subtract 1000 years from the expiry date to get the start date.

**Comment by CameronGoodwin** [comment]
Yes, what I was outlining works only for games that have some sort of online component.  If your app is intended to be simple and offline, then that won't work.

What I mean about multiple users if there are two users who each have a license to the app on the same device.  The API's are designed to give you the license information for how the game is running at the moment, so it has to decide which of the two licenses is the most correct or should take preference over the other.  Full-app license will always take priority over other types of licensing.  So if one had a trial and the other the full-app license, then the full-app license would be the one represented in the LicenseToken.  But if there are two full-app licenses, I am not positive on which one would take preference the oldest purchased one is my assumption.

**Comment by under3415** [comment]
That's really interesting, never thought about it before! 

Things work very different on Xbox and PC. If you buy an app on a PC, other users that log on to that PC do not get that app for free. Each user would have to buy it. But on Xbox, once a user buys a game (is it the same for non-games?), anyone on that console gets it for free. So the license on XBox is a combination of "per account" and "per console", where PC is always "per account".

**Comment by CameronGoodwin** [comment]
@under3415 That is mostly correct, but I was actually doing a separate investigation into LicenseTokens on PC yesterday and found some interesting information that was a bit different than what I explained above.

The PC and Xbox use slightly different licensing models, but they share some similarities.  Most of it is outlined in the now public documentation you can find here: [Product sharing model for games](https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/commerce/fundamentals/xstore-product-sharing-model-for-games)

The sharing mostly revolves around if a console is set as the HOME console of an account or similarly if a PC is set as the Offline PC of an account.  A user account can only specify one PC and one Xbox as each at a time.

If the PC is an Offline PC of account A, they just need to download the app and run it once I believe to get the offline license installed under that Windows User account.  Then they can switch which user is signed into the Store app and the license will still be there for them to launch and play the game.  On Xbox it is a bit easier, where the user who owns doesn't have to install or force the license down to the device first, it just knows what products it should be able to run through the HOME console sharing and allows anyone on that machine to install from the store directly even if they don't own it themselves.

The License API's that only return one object (XStoreAcquireGameLicenseAsync for example) should use the hierarchy logic that I described above as it can only return one value.  But the LicenseToken (XStoreQueryLicenseTokenAsync) actually contains all of the active licenses to the app or package on the PC.  So you can in those instances see multiple independent licenses.  The problem that I've found is that I have not found a way to understand what the UserId or Id's for each license map to.  So you just know that they are independent  But you don't know which one maps to which user.  So not sure that would help with your honeymoon trial period scenario that you listed above.  But wanted to make sure that I called that out regardless from what I found.
